services:
  postgres:
    image: postgres:14
    container_name: map-of-anime-postgres
    restart: unless-stopped
    ports:
      - "7001:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  etl-cron:
    build:
      context: ./data
      dockerfile: Dockerfile
    container_name: map-of-anime-etl-cron
    restart: unless-stopped
    environment:
      MAL_API_URL: ${MAL_API_URL}
      MAL_CLIENT_ID: ${MAL_CLIENT_ID}
      ELASTIC_URL: "elasticsearch:9200"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - ./data:/app:ro
    profiles:
      - infra

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: map-of-anime-elasticsearch
    restart: unless-stopped
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "true"
      xpack.security.transport.ssl.enabled: "false"
    ports:
      - "7002:9200"
      - "7003:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    profiles:
      - infra

  redis:
    image: redis:7
    container_name: map-of-anime-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "7004:6379"
    volumes:
      - redisdata:/data
    profiles:
      - infra

  map-of-anime:
    build:
      context: ./map-of-anime
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_URL: "postgres:5432"
      ELASTIC_URL: "elasticsearch:9200"
      REDIS_URL: "redis:6379"
    profiles:
      - deploy

volumes:
  pgdata:
  esdata:
  redisdata:
